config/routes.rb
Rails.application.routes.draw do


  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  scope module: :public do
    get "about" => "homes#about", as: 'about'
    resources :orders, only: [:new, :index, :show, :create] do
     collection do
      get "thanks" => "orders#thanks"
      post "confirm" => "orders#confirm"
     end
    end
    resources :customers, only: [:show, :edit, :update] do
     collection do
       get "out" => "customers#out"
       patch "destroyupdate" => "customers#destroyupdate"
     end
    end
    resources :addresses, only: [:index, :edit, :destroy, :create, :update]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :create, :destroy] do
     collection do
       delete "destroy_all" => "cart_items#destroy_all"
     end
    end
  end
   devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "orders#index"
    resources :orders, only: [:show, :update,]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:new, :index, :show, :edit, :create, :update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :order_details, only: [:update]
  end
  root to: "public/homes#top"
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  validates :name, presence: true
  validates :address, presence: true
  validates :postcode, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  validates :amount, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many:orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number, :email, presence: true


  def active_for_authentication?
    super && (is_deleted == false)
  end

  def full_name
    self.last_name+""+self.first_name
  end

  def full_name_kana
    self.last_name_kana+""+self.first_name_kana
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details

  has_one_attached :image
  def get_image
    if image.attached?
      image
    else
      'noimage.jpeg'
    end
  end

  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :genre_name, presence: true
  validates :price, presence: true
  validates :sale_status, presence: true
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details

  enum payment: { クレジットカード: 0, 口座振込: 1 }
  enum order_status: { 入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済:4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
	belongs_to :item

  enum production_status: { 製作不可:0, 製作待ち:1, 製作中:2, 製作完了:3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def new
    @genre = Genre.new
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to '/admin/genres'
  end

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
  end
end

private
  def genre_params
    params.require(:genre).permit(:name)
  end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      @item = Item.new
      render 'new'
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  def to_boolean
     if sale_status == "true"
       true
     elsif self == "false"
       false
     end
  end

  private
    def item_params
      params.require(:item).permit(:name, :introduction, :image, :price, :id, :genre_name, :sale_status)
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @orders = Order.all.page(params[:page])
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @total_price = 0
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.update(order_params)
    if @order.order_status  == "入金確認"
      @order_details.update_all(production_status: "製作待ち")
    end
      redirect_to admin_order_path(@order.id)
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
      admin_root_path
  end

  def after_sign_out_path_for(resource)
      new_admin_session_path
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :phone_number, :address])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/_form.html.erb
<%= form_with model: @genre, url: '/admin/genres', method: :post do |f| %>

  <p>ジャンル名</p>
  <%= f.text_field :name %>

  <%= f.submit '新規登録', class:"btn btn-group-sm btn-success" %>
<% end %>

app/views/admin/genres/_genrebox.html.erb
<table class="table table-bordered genrebox_table">
  <thead>
    <tr class="table-head">
    <th class="genrebox_head">ジャンル検索</th>
    </tr>
  </thead>
  <tbody>
    <% @genres.each do |genre| %>
    <tr>
      <td class="table-body">
        <span class="btn btn-group-sm btn-success"><%= genre.name %></span>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/genres/edit.html.erb
<h1>Admin::Genres#edit</h1>
<p>Find me in app/views/admin/genres/edit.html.erb</p>

app/views/admin/genres/index.html.erb
<div class="container">
  <h5>ジャンル一覧・追加</h5>
  <%= render 'form' %>

  <div class="container">
    <table class="table">
        <thead>
           <tr>
            <th>ジャンル</th>
           </tr>
        </thead>
        <tbody>
           <% @genres.each do |genre| %>
             <tr>
               <td>
                 <%= genre.name %>
               </td>
             </tr>
           <% end %>
        </tbody>
    </table>
 </div>
</div>

app/views/admin/genres/new.html.erb
<%= render 'genres/form', genre: @genre %>

app/views/admin/items/_error.html.erb
<% if @item.errors.any? %>
  <%= @item.errors.count %>件のエラーが発生しました
  <ul>
    <% @item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/admin/items/edit.html.erb
<div class="row">
  <div class="container">
    <h5>編集画面</h5>

    <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>

      <p>商品画像</p>
      <%= f.file_field :image, accept: "image/*" %>

      <p>商品名</p>
      <%= f.text_field :name %>

      <p>商品説明</p>
      <%= f.text_area :introduction %>

      <p>ジャンル</p>
      <%= f.collection_select :genre_name, Genre.all, :name, :name %>

    	<p>税抜価格</p>
    	<%= f.text_field :price %>円</br>

    	<div class="sale_status">
        <%= f.label :販売ステータス %>
        <div>
          <%= f.radio_button :sale_status, true %>
          <%= f.label :sale_status, '販売中', value: true %>
        </div>
        <div>
          <%= f.radio_button :sale_status, false %>
          <%= f.label :sale_status, '販売停止中', value: false %>
        </div>
      </div>

      <%= f.submit '変更を保存', class:"btn btn-group-sm btn-success" %>
    <% end %>
  </div>
</div>

app/views/admin/items/index.html.erb
<h3>商品一覧</h3>

<div class="container">
  <%= link_to "新規登録", new_admin_item_path, class:"btn btn-group-sm btn-success"%>
  <table class="table">
      <thead>
         <tr>
          <th>商品id</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
         </tr>
      </thead>
      <tbody>
         <% @items.each do |item| %>
           <tr>
             <td>
               <%= item.id %>
             </td>
             <td>
              <%= link_to item.name, admin_item_path(item.id) %>
             </td>
             <td>
               <%= item.price %>円
             </td>
             <td>
               <%= item.genre_name %>
             </td>
             <td>
               <% if item.sale_status == true %>
                 販売中
               <% else %>
                 販売停止中
               <% end %>
             </td>
           </tr>
         <% end %>
      </tbody>
  </table>
  　<p class="text-center"><%= paginate @items %></p>
</div>

app/views/admin/items/new.html.erb
<div class="cotainer">
  <div class="row">

    <%= render 'error', item: @item %>
    <div class="col-9 offset-1">
     <h4>商品新規登録</h4>
      <%= form_with model: @item, url: '/admin/items', method: :post do |f| %>
        <div>商品画像</div>
        <%= f.file_field :image, accept: "image/*" %>

        <div>商品名</div>
        <%= f.text_field :name %>

        <div>商品説明</div>
        <%= f.text_area :introduction %>

        <div>ジャンル</div>
        <%= f.collection_select :genre_name, Genre.all, :name, :name %>

      	<div>税抜価格</div>
      	<%= f.text_field :price %>円</br>

        <div class="sale_status">
          <p>販売ステータス</p>
          <div>
            <%= f.radio_button :sale_status, true %>
            <%= f.label :sale_status, '販売中', value: true %>
          </div>
          <div>
            <%= f.radio_button :sale_status, false %>
            <%= f.label :sale_status, '販売停止中', value: false %>
          </div>
        </div>
        <%= f.submit '新規登録', class:"btn btn-group-sm btn-success" %>
        <% end %>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="row">
  <div class="container">
    <h5>商品詳細</h5>

    <div class="col-xs-5">
      <%= image_tag @item.get_image, size: "250x150" %>
    </div>

    <div class="col-xs-7">
      <table class="table">
        <tr>
          <th>商品名</th>
          <th><%= @item.name %></th>
        </tr>
        <tr>
          <th>商品説明</th>
          <th><%= @item.introduction %></th>
        </tr>
        <tr>
          <th>ジャンル名</th>
          <th><%= @item.genre_name %></th>
        </tr>
        <tr>
          <th>税込価格（税抜価格）</th>
          <th><%= (@item.price * 1.1).floor %>円 (<%= @item.price %>)円 </th>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <th>
            <% if @item.sale_status == true %>
              販売中
            <% else %>
              販売停止中
            <% end %>
          </th>
        </tr>
      </table>
      <%= link_to "編集する", edit_admin_item_path(@item.id), class:"btn btn-group-sm btn-success" %>
    </div>
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
    <h3 class="col-12 offset-1">注文履歴一覧</h3>
    <table class="table">
      <thead>
        <tr>
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M:%S'),admin_order_path(order) %></td>
            <td><%= order.name %></td>
            <td>
              <% @sum = 0 %>
              <% order.order_details.all.each do |order_detail| %>
              <% @amount = order_detail.amount %>
              <% @sum += @amount %>
              <% end %>
              <%= @sum %>
            </td>
            <td><%= order.order_status %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="text-center"><%= paginate @orders %></div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">

  </div>
</div>


<h3>注文履歴詳細</h3>
<p><strong>購入者</strong></p>
<p><%= @order.name %></p>
<p><strong>注文日</strong></p>
<p><%= @order.created_at.strftime('%Y/%m/%d') %></p>
<p><strong>配送先</strong></p>
<p>
  <%= @order.postcode %>
  <%= @order.address %><br>
  <%= @order.name %>
</p>
<p><strong>支払方法</strong></p>
<p><%= @order.payment %></p>
<p><strong>注文ステータス</strong></p>
<p>
  <%= form_with model:@order, url: admin_order_path, method: :patch do |f| %>
    <%= f.select :order_status, Order.order_statuses.keys %>
    <%= f.submit "更新", class: "btn btn-success" %>
  <% end %>
</p>

<table class="table">
  <thead>
    <tr>
      <th>商品名</th>
      <th>単価（税込）</th>
      <th>数量</th>
      <th>小計</th>
      <th>製作ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @order_details.each do |order_detail| %>
      <tr>
        <td><%= order_detail.item.name %></td>
         <td><%= (order_detail.item.price * 1.1).to_i %></td>
        <td><%= order_detail.amount %></td>
        <td><%= (order_detail.item.price * 1.1).floor * order_detail.amount .to_i %></td>
        <%= form_with model:order_detail, url: admin_order_detail_path(order_detail), method: :patch do |f| %>
          <td><%= f.select :production_status,OrderDetail.production_statuses.keys %></td>
          <td><%= f.submit "更新",class: "btn btn-success" %></td>
        <% end %>
        <% @total_price +=  (order_detail.item.price * 1.1).floor * order_detail.amount %>
      </tr>
    <% end %>
  </tbody>
</table>

 <table class "table">
      <tr>
        <th>商品合計</th>
        <td><%= @total_price.to_s(:delimited) %>円</td>
      </tr>
      <tr>
        <th>送料</th>
        <td><%= @order.freight.to_s(:delimited) %>円</td>
      </tr>
      <tr>
        <th><strong>ご請求額</strong></th>
        <td><%= @order.total_cost.to_s(:delimited) %>円</td>
      </tr>
    </table>