config/routes.rb
Rails.application.routes.draw do


  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  scope module: :public do
    get "about" => "homes#about", as: 'about'
    resources :orders, only: [:new, :index, :show, :create] do
     collection do
      get "thanks" => "orders#thanks"
      post "confirm" => "orders#confirm"
     end
    end
    resources :customers, only: [:show, :edit, :update] do
     collection do
       get "out" => "customers#out"
       patch "destroyupdate" => "customers#destroyupdate"
     end
    end
    resources :addresses, only: [:index, :edit, :destroy, :create, :update]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :create, :destroy] do
     collection do
       delete "destroy_all" => "cart_items#destroy_all"
     end
    end
  end
   devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "orders#index"
    resources :orders, only: [:show, :update,]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:new, :index, :show, :edit, :create, :update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :order_details, only: [:update]
  end
  root to: "public/homes#top"
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  validates :name, presence: true
  validates :address, presence: true
  validates :postcode, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  validates :amount, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many:orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number, :email, presence: true


  def active_for_authentication?
    super && (is_deleted == false)
  end

  def full_name
    self.last_name+""+self.first_name
  end

  def full_name_kana
    self.last_name_kana+""+self.first_name_kana
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details

  has_one_attached :image
  def get_image
    if image.attached?
      image
    else
      'noimage.jpeg'
    end
  end

  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :genre_name, presence: true
  validates :price, presence: true
  validates :sale_status, presence: true
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details

  enum payment: { クレジットカード: 0, 口座振込: 1 }
  enum order_status: { 入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済:4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
	belongs_to :item

  enum production_status: { 製作不可:0, 製作待ち:1, 製作中:2, 製作完了:3 }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postcode, :address, :phone_number, :email, :is_deleted)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def new
    @genre = Genre.new
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to '/admin/genres'
  end

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
  end
end

private
  def genre_params
    params.require(:genre).permit(:name)
  end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      @item = Item.new
      render 'new'
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  def to_boolean
     if sale_status == "true"
       true
     elsif self == "false"
       false
     end
  end

  private
    def item_params
      params.require(:item).permit(:name, :introduction, :image, :price, :id, :genre_name, :sale_status)
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @orders = Order.all.page(params[:page])
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @total_price = 0
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.update(order_params)
    if @order.order_status  == "入金確認"
      @order_details.update_all(production_status: "製作待ち")
    end
      redirect_to admin_order_path(@order.id)
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :phone_number, :address])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="cotainer">
  <div class="row">
    <div class="col-9 offset-1">


    <h4 class="mt-3"><%= @customer.full_name %>さんの会員情報編集</h4>

    <%= form_with model: @customer, url: admin_customer_path,local:true do |f| %>
    <div>
      <%= f.label :id,"会員ID", class: "col-md-2 mt-4" %>
      <%= @customer.id %>
    </div>
    <div>
      <%= f.label :last_name,"氏名", class: "col-md-2 mt-2" %>
      <%= f.text_field :last_name,class: "form-control-sm mr-5" %>
      <%= f.text_field :first_name,class: "form-control-sm" %>
    </div>
    <div>
      <%= f.label :last_name_kana,"フリガナ", class: "col-md-2 mt-2" %>
      <%= f.text_field :last_name_kana,class: "form-control-sm mr-5" %>
      <%= f.text_field :first_name_kana,class: "form-control-sm" %>
    </div>
    <div>
      <%= f.label :postcode,"郵便番号", class: "col-md-2 mt-2" %>
      <%= f.text_field :postcode,class: "form-control-sm mr-5" %>
    </div>
    <div>
      <%= f.label :address,"住所", class: "col-md-2 mt-2" %>
      <%= f.text_field :address,class: "form-control-sm mr-5" %>
    </div>
    <div>
      <%= f.label :phone_number,"電話番号", class: "col-md-2 mt-2" %>
      <%= f.text_field :phone_number,class: "form-control-sm mr-5" %>
    </div>
    <div>
      <%= f.label :email,"メールアドレス", class: "col-md-2 mt-2" %>
      <%= f.text_field :email,class: "form-control-sm mr-5" %>
    </div>
    <div>
      <%= f.label :is_deleted, "会員ステータス", class: "col-md-2 mt-2" %>
      <div class="form-check form-check-inline">
        <%= f.radio_button :is_deleted, false %>
        <%= f.label :is_deleted,"有効", value: false %>
      </div>
      <div class="form-check form-check-inline">
      <%= f.radio_button :is_deleted, true %>
      <%= f.label :is_deleted,"退会", value: true %>
      </div>
    </div>

    <%= f.submit "編集内容を保存", class: "btn btn-sm btn-success mt-4 offset-2" %>
    <% end %>

    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="cotainer">
  <div class="row">
    <div class="col-8 offset-1">

    <h4 class="mt-3 offset-1">会員一覧</h4>
    <table class="table table-sm mt-3">
      <thead>
        <tr>
          <th class="table-active col-1">会員ID</th>
          <th class="table-active col-2">氏名</th>
          <th class="table-active col-3">メールアドレス</th>
          <th class="table-active col-1">ステータス</th>

        </tr>
      </thead>
      <% @customers.each do |customer| %>
      <tbody>
        <tr>
          <td><%= customer.id %></td>
          <td>
            <%= link_to admin_customer_path(customer.id) do %>
            <%= customer.full_name %>
            <% end %>
          </td>
          <td><%= customer.email %></td>
          <% if customer.is_deleted == false %>
          <td class="text-success">有効</td>
          <% else %>
          <td class="text-secondary">退会</td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="offset-5"><%= paginate @customers %></div>
    </div>

  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="cotainer">
  <div class="row">
    <div class="col-md-9 offset-1">

    <h4 class="mt-3 mb-4"><%= @customer.full_name %>さんの会員詳細</h4>
      <table class="table table-bordered col-6">
        <tr>
          <th class="col-4">会員ID</th>
          <th><%= @customer.id %></th>
        </tr>
        <tr>
          <th class="col-4">氏名</th>
          <th><%= @customer.full_name %></th>
        </tr>
        <tr>
          <th class="col-4">カナ</th>
          <th><%= @customer.full_name_kana %></th>
        </tr>
        <tr>
          <th class="col-4">郵便番号</th>
          <th><%= @customer.postcode %></th>
        </tr>
        <tr>
          <th class="col-4">住所</th>
          <th><%= @customer.address %></th>
        </tr>
        <tr>
          <th class="col-4">電話番号</th>
          <th><%= @customer.phone_number %></th>
        </tr>
        <tr>
          <th class="col-4">メールアドレス</th>
          <th><%= @customer.email %></th>
        </tr>
        <tr>
          <th class="col-4 mt-5">会員ステータス</th>
          <% if @customer.is_deleted == false %>
          <th class="text-success">有効</th>
          <% else %>
          <th class="text-secondary">退会</th>
          <% end %>
        </tr>
      </table>
        <div>
          <%= link_to "編集する", edit_admin_customer_path, class: "btn btn-sm btn-success mt-3 offset-2 mr-5" %>
          <%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn btn-sm btn-primary mt-3" %>
        </div>


    </div>
  </div>
</div>