config/routes.rb
Rails.application.routes.draw do


  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  scope module: :public do
    get "about" => "homes#about", as: 'about'
    resources :orders, only: [:new, :index, :show, :create] do
     collection do
      get "thanks" => "orders#thanks"
      post "confirm" => "orders#confirm"
     end
    end
    resources :customers, only: [:show, :edit, :update] do
     collection do
       get "out" => "customers#out"
       patch "destroyupdate" => "customers#destroyupdate"
     end
    end
    resources :addresses, only: [:index, :edit, :destroy, :create, :update]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :create, :destroy] do
     collection do
       delete "destroy_all" => "cart_items#destroy_all"
     end
    end
  end
   devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "orders#index"
    resources :orders, only: [:show, :update,]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:new, :index, :show, :edit, :create, :update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :order_details, only: [:update]
  end
  root to: "public/homes#top"
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  validates :name, presence: true
  validates :address, presence: true
  validates :postcode, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  validates :amount, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many:orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number, :email, presence: true


  def active_for_authentication?
    super && (is_deleted == false)
  end

  def full_name
    self.last_name+""+self.first_name
  end

  def full_name_kana
    self.last_name_kana+""+self.first_name_kana
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details

  has_one_attached :image
  def get_image
    if image.attached?
      image
    else
      'noimage.jpeg'
    end
  end

  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :genre_name, presence: true
  validates :price, presence: true
  validates :sale_status, presence: true
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details

  enum payment: { クレジットカード: 0, 口座振込: 1 }
  enum order_status: { 入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済:4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
	belongs_to :item

  enum production_status: { 製作不可:0, 製作待ち:1, 製作中:2, 製作完了:3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def new
    @genre = Genre.new
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to '/admin/genres'
  end

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
  end
end

private
  def genre_params
    params.require(:genre).permit(:name)
  end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      @item = Item.new
      render 'new'
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  def to_boolean
     if sale_status == "true"
       true
     elsif self == "false"
       false
     end
  end

  private
    def item_params
      params.require(:item).permit(:name, :introduction, :image, :price, :id, :genre_name, :sale_status)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :phone_number, :address])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<headar>
  <nav class="navbar navbar-expand-lg navbar-right pb-4 border-bottom border-dark">
    <div class="container">
      <div>
        <%= link_to root_path do %>
        <%= image_tag 'herder.jpg', :size => '350x80' %>
        <% end %>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse collapse show" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if customer_signed_in? %>

          <li>ようこそ<%= current_customer.last_name %>さん！</li>
          <li><%= link_to "マイページ", customer_path(current_customer),class: 'btn btn-sm btn-outline-secondary bg-success text-white ' %></li>
          <li><%= link_to "商品一覧", items_path,class: 'btn btn-sm btn-outline-secondary bg-success text-white' %></li>
          <li><%= link_to "カート", cart_item_path(current_customer.cart_items.count),class: 'btn btn-sm btn-outline-secondary bg-success text-white' %></li>
          <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete,class: 'btn btn-sm btn-outline-secondary bg-success text-white' %></li>

        <% elsif admin_signed_in? %>
          <li><%= link_to "商品一覧", admin_items_path, class: 'btn btn-sm btn-outline-secondary bg-success text-white' %></li>
          <li><%= link_to "会員一覧", admin_customers_path, class: 'btn btn-sm btn-outline-secondary bg-success text-white' %></li>
          <li><%= link_to "注文履歴一覧", admin_root_path, class: 'btn btn-sm btn-outline-secondary bg-success text-white' %></li>
          <li><%= link_to "ジャンル一覧", admin_genres_path, class: 'btn btn-sm btn-outline-secondary bg-success text-white' %></li>
          <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-sm btn-outline-secondary bg-success text-white' %></li>

        <% else %>
          <li><%= link_to "About", about_path,class: 'btn btn-sm btn-outline-secondary bg-success text-white ' %></li>
          <li><%= link_to "商品一覧", items_path,class: 'btn btn-sm btn-outline-secondary bg-success text-white' %></li>
          <li><%= link_to "新規登録", new_customer_registration_path,class: 'btn btn-sm btn-outline-secondary bg-success text-white' %></li>
          <li><%= link_to "ログイン", new_customer_session_path ,class: 'btn btn-sm btn-outline-secondary bg-success text-white' %></li>
        <% end %>
        </ul>
      </div>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-secondary" type="submit">Search</button>
      </form>
    </div>
  </nav>
</headar>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <footer>
      <nav class="navbar navbar-expand-md navbar-right pb-4 border-top border-dark">
        <div style="text-align: center">
          <div>Copyright © 2022 NaganoCake All Rights Reserved.</div>
      　</div>
      </nav>
    </footer>
  </body>

</html>